const contactText =`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. A pellentesque sit amet porttitor. Amet venenatis urna cursus eget. Elit sed vulputate mi sit amet mauris commodo quis. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Risus commodo viverra maecenas accumsan. Vitae semper quis lectus nulla at volutpat. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Commodo ullamcorper a lacus vestibulum sed arcu non. Ac felis donec et odio pellentesque. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae.

    Sem nulla pharetra diam sit amet. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Integer vitae justo eget magna fermentum. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Lacinia quis vel eros donec. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Integer eget aliquet nibh praesent tristique magna sit amet. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Enim eu turpis egestas pretium aenean pharetra. Parturient montes nascetur ridiculus mus mauris vitae. Justo laoreet sit amet cursus. Eu sem integer vitae justo eget magna fermentum iaculis. Amet dictum sit amet justo donec enim diam vulputate ut. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Id porta nibh venenatis cras sed. Nec ullamcorper sit amet risus.

    Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Purus viverra accumsan in nisl nisi scelerisque eu. Elit scelerisque mauris pellentesque pulvinar. Facilisi nullam vehicula ipsum a arcu cursus. Mollis aliquam ut porttitor leo a diam sollicitudin. Ac orci phasellus egestas tellus rutrum tellus. Quisque non tellus orci ac auctor augue mauris augue. Pellentesque sit amet porttitor eget. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Tristique senectus et netus et malesuada.

    Eget magna fermentum iaculis eu non diam. Diam quis enim lobortis scelerisque. Eu facilisis sed odio morbi quis commodo odio. Odio eu feugiat pretium nibh ipsum consequat nisl vel. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Convallis posuere morbi leo urna molestie at elementum eu. Enim eu turpis egestas pretium aenean pharetra magna ac. Sed elementum tempus egestas sed. Quis eleifend quam adipiscing vitae proin. Nunc non blandit massa enim nec dui. Tortor dignissim convallis aenean et tortor at risus.

    Morbi non arcu risus quis varius quam quisque. Arcu dui vivamus arcu felis bibendum ut tristique et. Mauris a diam maecenas sed. Congue quisque egestas diam in. Tellus id interdum velit laoreet id donec ultrices. Ornare suspendisse sed nisi lacus. Auctor elit sed vulputate mi sit amet. Semper viverra nam libero justo laoreet. Tellus pellentesque eu tincidunt tortor aliquam nulla. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Ipsum consequat nisl vel pretium. Ornare arcu odio ut sem nulla.`




export default contactText;